# PRIVATE WORKAROUND BECAUSE OF MISSING TWRP -> BUILDIN PICO GAPPS
# PRIVATE WORKAROUND BECAUSE OF MISSING TWRP -> BUILDIN PICO GAPPS
# PRIVATE WORKAROUND BECAUSE OF MISSING TWRP -> BUILDIN PICO GAPPS
# PRIVATE WORKAROUND BECAUSE OF MISSING TWRP -> BUILDIN PICO GAPPS
# PRIVATE WORKAROUND BECAUSE OF MISSING TWRP -> BUILDIN PICO GAPPS
# OpenGapps
# Make it buildable in AOSP 10 with the new PATH Tools restrictions
# Error -> Disallowed PATH tool "locale" used: []string{"locale", "-a"}
TEMPORARY_DISABLE_PATH_RESTRICTIONS=true

GAPPS_VARIANT := pico

$(call inherit-product-if-exists, vendor/opengapps/build/opengapps-packages.mk)
